"""Writes server/functions/index.js: a static map of every server function, so the
Vercel bundler includes them all behind the single /api/fn/[name] route."""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = os.path.join(ROOT, 'server/functions')
names = sorted(f[:-3] for f in os.listdir(D) if f.endswith('.js') and f != 'index.js')
lines = ["// Generated by scripts/gen_registry.py. Add a file to server/functions and re-run.", "export const FUNCTIONS = {"]
lines += [f"  {n}: () => import('./{n}.js')," for n in names]
lines += ["};", ""]
open(os.path.join(D, 'index.js'), 'w').write("\n".join(lines))
print(len(names), 'functions registered')
