"""Single source for roles and permissions (Brokermint-style).

Generates:
  supabase/migrations/0005_permissions.sql  (SQL: public.perm_default(role, key), public.has_perm(key))
  shared/permissions.generated.js           (same table for the app)

Run: python3 scripts/gen_permissions.py
"""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ROLES = {
    "owner": "Owner",
    "broker": "Broker",
    "office_admin": "Office administrator",
    "team_leader": "Team leader",
    "tc": "Transaction coordinator",
    "agent": "Agent",
}
# Legacy role names from Base44
ALIASES = {"admin": "office_admin", "user": "agent", "super_admin": "owner"}

# key: (group, label, roles that get it by default)
ALL = set(ROLES)
ADMINS = {"owner", "broker", "office_admin"}
AGENTISH = {"agent", "team_leader", "tc"}
PERMS = {
    "tx.create":            ("Transactions", "Can create transactions", ALL),
    "tx.edit":              ("Transactions", "Can edit transactions", ALL),
    "tx.delete":            ("Transactions", "Can delete transactions", ADMINS),
    "tx.cancel":            ("Transactions", "Can cancel transactions", ALL),
    "tx.all":               ("Transactions", "Can access all company transactions", ADMINS),
    "tx.checklist_manage":  ("Transactions", "Can manage transaction checklist tasks", ADMINS | {"tc"}),
    "tx.checklist_add":     ("Transactions", "Can add checklists to transaction", ALL),
    "tx.checklist_remove":  ("Transactions", "Can remove checklists from transaction", ADMINS | {"tc"}),
    "tx.close":             ("Transactions", "Can close transactions", ADMINS | {"tc"}),
    "tx.reopen":            ("Transactions", "Can re-open transactions", ADMINS),
    "tx.edit_emd":          ("Transactions", "Can edit earnest money deposit", ALL),
    "tx.view_commissions":  ("Transactions", "Can view transaction commissions", ALL),
    "tx.share":             ("Transactions", "Can share transactions (add co-agents)", ALL),
    "offers.access":        ("Buyer offers", "Can access buyer offers", ALL),
    "offers.create":        ("Buyer offers", "Can create buyer offers", ALL),
    "offers.edit":          ("Buyer offers", "Can edit buyer offers", ALL),
    "offers.delete":        ("Buyer offers", "Can delete buyer offers", ALL),
    "offers.all":           ("Buyer offers", "Can access all company buyer offers", ADMINS),
    "pipeline.individual":  ("Reports", "Can see individual pipeline", ALL),
    "reports.personal":     ("Reports", "Can access personal reports", ALL),
    "reports.company":      ("Reports", "Can access company reports", ADMINS),
    "contacts.private_all": ("Contacts", "Can access private contacts", ADMINS),
    "activity.account":     ("Activity", "Can access account activity", ADMINS),
    "activity.transaction": ("Activity", "Can access transaction activity", ALL),
    "library.access":       ("Library", "Can access library", ALL),
    "library.manage":       ("Library", "Can manage library", ADMINS),
    "library.private_all":  ("Library", "Can access all private folders", ADMINS),
    "docs.approve":         ("Documents", "Can approve documents", ADMINS),
    "docs.approve2":        ("Documents", "Can second level approve documents", {"owner", "broker"}),
    "docs.submit_tx":       ("Documents", "Can submit transactions for approval", ALL),
    "docs.submit_individual": ("Documents", "Can submit individual documents", ALL),
    "settings.manage":      ("Settings", "Can manage company settings", {"owner", "broker"}),
    "accounting.access":    ("Accounting", "Can access accounting (commissions, payouts)", {"owner", "broker", "office_admin"}),
    "users.manage":         ("Settings", "Can manage users", ADMINS),
}

# ---- SQL
cases = []
for key, (_, _, roles) in PERMS.items():
    rl = ",".join(f"'{r}'" for r in sorted(roles))
    cases.append(f"    when '{key}' then r in ({rl})")
alias_sql = " ".join(f"when '{a}' then '{b}'" for a, b in ALIASES.items())
sql = f"""-- Roles and permissions. Generated by scripts/gen_permissions.py; edit that file.
-- Per-user overrides live in profiles.permissions ({{"tx.all": true, ...}}).

create or replace function public.perm_default(role text, key text) returns boolean language sql immutable as $$
  select case key
{chr(10).join(cases)}
    else false end
  from (select public.normalize_role(role) as r) x
$$;

create or replace function public.has_perm(key text) returns boolean
language sql stable security definer set search_path = public as $$
  select coalesce(
    (select case when p.permissions ? key then (p.permissions ->> key)::boolean
                 else public.perm_default(p.role, key) end
       from public.profiles p where p.id = auth.uid() and public.second_step_ok()),
    false)
$$;

create or replace function public.auth_team_id() returns text
language sql stable security definer set search_path = public as $$
  select team_id from public.profiles where id = auth.uid() and public.second_step_ok()
$$;
create or replace function public.is_team_leader() returns boolean language sql stable as $$
  select coalesce(public.normalize_role(public.auth_role()) = 'team_leader', false)
$$;
-- Team leaders see their team members' deals.
create or replace function public.leads_agent(agent_email text) returns boolean
language sql stable security definer set search_path = public as $$
  select public.is_team_leader() and public.auth_team_id() is not null and exists (
    select 1 from public.profiles p where lower(p.email) = lower(agent_email) and p.team_id = public.auth_team_id())
$$;
"""
# Included into 0001_init.sql by gen_schema.py (policies need these functions to exist).
open(os.path.join(ROOT, "scripts/permissions.sql.part"), "w").write(sql)

js = {
    "ROLES": ROLES,
    "ALIASES": ALIASES,
    "PERMS": {k: {"group": g, "label": l, "roles": sorted(r)} for k, (g, l, r) in PERMS.items()},
}
open(os.path.join(ROOT, "shared/permissions.generated.js"), "w").write(
    "// Generated by scripts/gen_permissions.py. Roles and permissions shared by app and server.\n"
    f"export const ROLES = {json.dumps(ROLES, indent=2)};\n"
    f"export const ROLE_ALIASES = {json.dumps(ALIASES)};\n"
    f"export const PERMS = {json.dumps(js['PERMS'], indent=2)};\n"
    """
export const normalizeRole = (r) => ROLE_ALIASES[r] || r || 'agent';
export const ADMIN_ROLE_SET = new Set(['owner', 'broker', 'office_admin']);
export const isAdminRole = (r) => ADMIN_ROLE_SET.has(normalizeRole(r)) || r === 'super_admin';

/** Does this profile have the permission? Per-user overrides win over role defaults. */
export function can(profile, key) {
  if (!profile) return false;
  if (profile.role === 'super_admin') return true;
  const o = profile.permissions || {};
  if (Object.prototype.hasOwnProperty.call(o, key)) return !!o[key];
  return (PERMS[key]?.roles || []).includes(normalizeRole(profile.role));
}
""")
print(len(PERMS), "permissions,", len(ROLES), "roles")
