-- Go Broker Hub schema. Generated by scripts/gen_schema.py; edit that file, not this one.
-- Run once in the Supabase SQL editor (or `supabase db push`).

create extension if not exists pgcrypto;

-- Users -------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  full_name text,
  display_name text,
  role text not null default 'user',
  brokerage_id text,
  suspended boolean default false,
  headshot text,
  agent_status text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);

-- Create a profile row whenever someone signs up
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name', ''))
  on conflict (id) do nothing;
  return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- Helpers used by the security policies
create or replace function public.auth_email() returns text language sql stable as $$
  select lower(coalesce(auth.jwt()->>'email', ''))
$$;
create or replace function public.auth_brokerage_id() returns text
language sql stable security definer set search_path = public as $$
  select brokerage_id from public.profiles where id = auth.uid()
$$;
create or replace function public.auth_role() returns text
language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid()
$$;
create or replace function public.is_super_admin() returns boolean language sql stable as $$
  select coalesce(public.auth_role() = 'super_admin', false)
$$;
create or replace function public.is_brokerage_admin() returns boolean language sql stable as $$
  select coalesce(public.auth_role() in ('admin','broker','super_admin'), false)
$$;

create or replace function public.touch_updated_date() returns trigger language plpgsql as $$
begin new.updated_date = now(); return new; end $$;

-- Base44 filled these in automatically; keep doing that so records never go missing
-- from a brokerage because a screen forgot to send brokerage_id.
create or replace function public.fill_owner() returns trigger language plpgsql as $$
begin
  if new.created_by is null then new.created_by := nullif(public.auth_email(), ''); end if;
  if new.brokerage_id is null then new.brokerage_id := public.auth_brokerage_id(); end if;
  return new;
end $$;
create or replace function public.fill_creator() returns trigger language plpgsql as $$
begin
  if new.created_by is null then new.created_by := nullif(public.auth_email(), ''); end if;
  return new;
end $$;

alter table public.profiles enable row level security;
drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select using (
  id = auth.uid() or brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles for update using (id = auth.uid())
  with check (id = auth.uid()
    and role = public.auth_role()
    and brokerage_id is not distinct from public.auth_brokerage_id());
-- Joining a brokerage or changing roles goes through server routes (service role).
drop policy if exists profiles_admin on public.profiles;
create policy profiles_admin on public.profiles for update using (
  (public.is_brokerage_admin() and brokerage_id = public.auth_brokerage_id()) or public.is_super_admin())
  with check (public.is_super_admin() or (role <> 'super_admin' and brokerage_id = public.auth_brokerage_id()));
drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles for each row execute function public.touch_updated_date();

-- ActivityLog -----------------------------------------------------------
create table if not exists public.activity_log (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  action_type text,
  brokerage_id text,
  browser text,
  details jsonb,
  document_id text,
  ip_address text,
  location text,
  os text,
  user_agent text,
  user_email text,
  user_name text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists activity_log_touch on public.activity_log;
create trigger activity_log_touch before update on public.activity_log for each row execute function public.touch_updated_date();
drop trigger if exists activity_log_fill on public.activity_log;
create trigger activity_log_fill before insert on public.activity_log for each row execute function public.fill_owner();
alter table public.activity_log enable row level security;
create index if not exists activity_log_brokerage_id_idx on public.activity_log (brokerage_id);
create index if not exists activity_log_user_email_idx on public.activity_log (user_email);
create index if not exists activity_log_document_id_idx on public.activity_log (document_id);

-- AdminMessage ----------------------------------------------------------
create table if not exists public.admin_message (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  content text,
  sender_email text,
  sender_name text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists admin_message_touch on public.admin_message;
create trigger admin_message_touch before update on public.admin_message for each row execute function public.touch_updated_date();
drop trigger if exists admin_message_fill on public.admin_message;
create trigger admin_message_fill before insert on public.admin_message for each row execute function public.fill_owner();
alter table public.admin_message enable row level security;
create index if not exists admin_message_brokerage_id_idx on public.admin_message (brokerage_id);

-- AgentSales ------------------------------------------------------------
create table if not exists public.agent_sales (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  agent_email text,
  agent_id text,
  agent_name text,
  brokerage_id text,
  month text,
  sales_amount numeric,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists agent_sales_touch on public.agent_sales;
create trigger agent_sales_touch before update on public.agent_sales for each row execute function public.touch_updated_date();
drop trigger if exists agent_sales_fill on public.agent_sales;
create trigger agent_sales_fill before insert on public.agent_sales for each row execute function public.fill_owner();
alter table public.agent_sales enable row level security;
create index if not exists agent_sales_brokerage_id_idx on public.agent_sales (brokerage_id);

-- Brokerage -------------------------------------------------------------
create table if not exists public.brokerage (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  account_owner_id text,
  broker_name text,
  broker_title text,
  email text,
  name text,
  phone text,
  status text,
  welcome_message text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists brokerage_touch on public.brokerage;
create trigger brokerage_touch before update on public.brokerage for each row execute function public.touch_updated_date();
drop trigger if exists brokerage_fill on public.brokerage;
create trigger brokerage_fill before insert on public.brokerage for each row execute function public.fill_creator();
alter table public.brokerage enable row level security;

-- BrokerageSettings -----------------------------------------------------
create table if not exists public.brokerage_settings (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  brokerage_phone text,
  logo_url text,
  tech_links jsonb,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists brokerage_settings_touch on public.brokerage_settings;
create trigger brokerage_settings_touch before update on public.brokerage_settings for each row execute function public.touch_updated_date();
drop trigger if exists brokerage_settings_fill on public.brokerage_settings;
create trigger brokerage_settings_fill before insert on public.brokerage_settings for each row execute function public.fill_owner();
alter table public.brokerage_settings enable row level security;
create index if not exists brokerage_settings_brokerage_id_idx on public.brokerage_settings (brokerage_id);

-- CMAsReport ------------------------------------------------------------
create table if not exists public.cmas_report (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  address text,
  bathrooms integer,
  bedrooms integer,
  brokerage_id text,
  cma_report jsonb,
  notes text,
  status text,
  title text,
  user_email text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists cmas_report_touch on public.cmas_report;
create trigger cmas_report_touch before update on public.cmas_report for each row execute function public.touch_updated_date();
drop trigger if exists cmas_report_fill on public.cmas_report;
create trigger cmas_report_fill before insert on public.cmas_report for each row execute function public.fill_owner();
alter table public.cmas_report enable row level security;
create index if not exists cmas_report_brokerage_id_idx on public.cmas_report (brokerage_id);
create index if not exists cmas_report_user_email_idx on public.cmas_report (user_email);

-- Channel ---------------------------------------------------------------
create table if not exists public.channel (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  emoji text,
  label text,
  name text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists channel_touch on public.channel;
create trigger channel_touch before update on public.channel for each row execute function public.touch_updated_date();
drop trigger if exists channel_fill on public.channel;
create trigger channel_fill before insert on public.channel for each row execute function public.fill_owner();
alter table public.channel enable row level security;
create index if not exists channel_brokerage_id_idx on public.channel (brokerage_id);

-- ChannelMember ---------------------------------------------------------
create table if not exists public.channel_member (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  channel_id text,
  user_email text,
  user_name text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists channel_member_touch on public.channel_member;
create trigger channel_member_touch before update on public.channel_member for each row execute function public.touch_updated_date();
drop trigger if exists channel_member_fill on public.channel_member;
create trigger channel_member_fill before insert on public.channel_member for each row execute function public.fill_owner();
alter table public.channel_member enable row level security;
create index if not exists channel_member_brokerage_id_idx on public.channel_member (brokerage_id);
create index if not exists channel_member_user_email_idx on public.channel_member (user_email);

-- ClientReview ----------------------------------------------------------
create table if not exists public.client_review (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  agent_email text,
  agent_id text,
  agent_name text,
  brokerage_id text,
  client_name text,
  comment text,
  property_address text,
  rating integer,
  reactions jsonb,
  review_token text,
  status text,
  submitted boolean,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists client_review_touch on public.client_review;
create trigger client_review_touch before update on public.client_review for each row execute function public.touch_updated_date();
drop trigger if exists client_review_fill on public.client_review;
create trigger client_review_fill before insert on public.client_review for each row execute function public.fill_owner();
alter table public.client_review enable row level security;
create index if not exists client_review_brokerage_id_idx on public.client_review (brokerage_id);
create index if not exists client_review_review_token_idx on public.client_review (review_token);

-- Comment ---------------------------------------------------------------
create table if not exists public.comment (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  author_email text,
  author_name text,
  brokerage_id text,
  content text,
  idea_id text,
  mentions jsonb,
  parent_comment_id text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists comment_touch on public.comment;
create trigger comment_touch before update on public.comment for each row execute function public.touch_updated_date();
drop trigger if exists comment_fill on public.comment;
create trigger comment_fill before insert on public.comment for each row execute function public.fill_owner();
alter table public.comment enable row level security;
create index if not exists comment_brokerage_id_idx on public.comment (brokerage_id);

-- ComplianceAttempt -----------------------------------------------------
create table if not exists public.compliance_attempt (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  agent_email text,
  answers jsonb,
  brokerage_id text,
  passed boolean,
  score integer,
  training_id text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists compliance_attempt_touch on public.compliance_attempt;
create trigger compliance_attempt_touch before update on public.compliance_attempt for each row execute function public.touch_updated_date();
drop trigger if exists compliance_attempt_fill on public.compliance_attempt;
create trigger compliance_attempt_fill before insert on public.compliance_attempt for each row execute function public.fill_owner();
alter table public.compliance_attempt enable row level security;
create index if not exists compliance_attempt_brokerage_id_idx on public.compliance_attempt (brokerage_id);

-- ComplianceQuestion ----------------------------------------------------
create table if not exists public.compliance_question (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  correct_answer text,
  explanation text,
  options jsonb,
  "order" integer,
  question_text text,
  question_type text,
  training_id text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists compliance_question_touch on public.compliance_question;
create trigger compliance_question_touch before update on public.compliance_question for each row execute function public.touch_updated_date();
drop trigger if exists compliance_question_fill on public.compliance_question;
create trigger compliance_question_fill before insert on public.compliance_question for each row execute function public.fill_creator();
alter table public.compliance_question enable row level security;

-- ComplianceTraining ----------------------------------------------------
create table if not exists public.compliance_training (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  category text,
  description text,
  passing_score integer,
  title text,
  type text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists compliance_training_touch on public.compliance_training;
create trigger compliance_training_touch before update on public.compliance_training for each row execute function public.touch_updated_date();
drop trigger if exists compliance_training_fill on public.compliance_training;
create trigger compliance_training_fill before insert on public.compliance_training for each row execute function public.fill_owner();
alter table public.compliance_training enable row level security;
create index if not exists compliance_training_brokerage_id_idx on public.compliance_training (brokerage_id);

-- Conversation ----------------------------------------------------------
create table if not exists public.conversation (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  agent_email text,
  agent_name text,
  broker_email text,
  brokerage_id text,
  category text,
  handled_by text,
  last_message_preview text,
  status text,
  summary text,
  tags jsonb,
  title text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists conversation_touch on public.conversation;
create trigger conversation_touch before update on public.conversation for each row execute function public.touch_updated_date();
drop trigger if exists conversation_fill on public.conversation;
create trigger conversation_fill before insert on public.conversation for each row execute function public.fill_owner();
alter table public.conversation enable row level security;
create index if not exists conversation_brokerage_id_idx on public.conversation (brokerage_id);

-- CultureCalendarEntry --------------------------------------------------
create table if not exists public.culture_calendar_entry (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  created_by_email text,
  created_by_name text,
  date date,
  description text,
  event_type text,
  month text,
  person_email text,
  person_name text,
  title text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists culture_calendar_entry_touch on public.culture_calendar_entry;
create trigger culture_calendar_entry_touch before update on public.culture_calendar_entry for each row execute function public.touch_updated_date();
drop trigger if exists culture_calendar_entry_fill on public.culture_calendar_entry;
create trigger culture_calendar_entry_fill before insert on public.culture_calendar_entry for each row execute function public.fill_owner();
alter table public.culture_calendar_entry enable row level security;
create index if not exists culture_calendar_entry_brokerage_id_idx on public.culture_calendar_entry (brokerage_id);

-- CultureCalendarRSVP ---------------------------------------------------
create table if not exists public.culture_calendar_rsvp (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  culture_calendar_entry_id text,
  response_date timestamptz,
  status text,
  user_email text,
  user_name text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists culture_calendar_rsvp_touch on public.culture_calendar_rsvp;
create trigger culture_calendar_rsvp_touch before update on public.culture_calendar_rsvp for each row execute function public.touch_updated_date();
drop trigger if exists culture_calendar_rsvp_fill on public.culture_calendar_rsvp;
create trigger culture_calendar_rsvp_fill before insert on public.culture_calendar_rsvp for each row execute function public.fill_owner();
alter table public.culture_calendar_rsvp enable row level security;
create index if not exists culture_calendar_rsvp_brokerage_id_idx on public.culture_calendar_rsvp (brokerage_id);
create index if not exists culture_calendar_rsvp_user_email_idx on public.culture_calendar_rsvp (user_email);

-- DashboardAnnouncement -------------------------------------------------
create table if not exists public.dashboard_announcement (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  audio_url text,
  brokerage_id text,
  message text,
  posted_by_email text,
  posted_by_name text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists dashboard_announcement_touch on public.dashboard_announcement;
create trigger dashboard_announcement_touch before update on public.dashboard_announcement for each row execute function public.touch_updated_date();
drop trigger if exists dashboard_announcement_fill on public.dashboard_announcement;
create trigger dashboard_announcement_fill before insert on public.dashboard_announcement for each row execute function public.fill_owner();
alter table public.dashboard_announcement enable row level security;
create index if not exists dashboard_announcement_brokerage_id_idx on public.dashboard_announcement (brokerage_id);

-- DirectMessage ---------------------------------------------------------
create table if not exists public.direct_message (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  content text,
  reactions jsonb,
  read boolean,
  receiver_email text,
  receiver_id text,
  receiver_name text,
  receiver_photo text,
  sender_email text,
  sender_id text,
  sender_name text,
  sender_photo text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists direct_message_touch on public.direct_message;
create trigger direct_message_touch before update on public.direct_message for each row execute function public.touch_updated_date();
drop trigger if exists direct_message_fill on public.direct_message;
create trigger direct_message_fill before insert on public.direct_message for each row execute function public.fill_owner();
alter table public.direct_message enable row level security;
create index if not exists direct_message_brokerage_id_idx on public.direct_message (brokerage_id);

-- DocumentTemplate ------------------------------------------------------
create table if not exists public.document_template (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  is_active boolean,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists document_template_touch on public.document_template;
create trigger document_template_touch before update on public.document_template for each row execute function public.touch_updated_date();
drop trigger if exists document_template_fill on public.document_template;
create trigger document_template_fill before insert on public.document_template for each row execute function public.fill_owner();
alter table public.document_template enable row level security;
create index if not exists document_template_brokerage_id_idx on public.document_template (brokerage_id);

-- ESignAuditLog ---------------------------------------------------------
create table if not exists public.esign_audit_log (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  action text,
  details jsonb,
  document_id text,
  ip_address text,
  signer_email text,
  user_agent text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists esign_audit_log_touch on public.esign_audit_log;
create trigger esign_audit_log_touch before update on public.esign_audit_log for each row execute function public.touch_updated_date();
drop trigger if exists esign_audit_log_fill on public.esign_audit_log;
create trigger esign_audit_log_fill before insert on public.esign_audit_log for each row execute function public.fill_creator();
alter table public.esign_audit_log enable row level security;
create index if not exists esign_audit_log_document_id_idx on public.esign_audit_log (document_id);

-- ESignDocument ---------------------------------------------------------
create table if not exists public.esign_document (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  algorithm text,
  audit_trail_pdf_url text,
  brokerage_id text,
  created_by_email text,
  created_by_name text,
  description text,
  document_hash text,
  document_url text,
  encrypted boolean,
  encryption_metadata jsonb,
  fields jsonb,
  final_signed_document_url text,
  iv text,
  name text,
  original_document_url text,
  require_sequential_signing boolean,
  signatories jsonb,
  signature_fields jsonb,
  signers jsonb,
  slug text,
  status text,
  title text,
  version integer,
  versions jsonb,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists esign_document_touch on public.esign_document;
create trigger esign_document_touch before update on public.esign_document for each row execute function public.touch_updated_date();
drop trigger if exists esign_document_fill on public.esign_document;
create trigger esign_document_fill before insert on public.esign_document for each row execute function public.fill_owner();
alter table public.esign_document enable row level security;
create index if not exists esign_document_brokerage_id_idx on public.esign_document (brokerage_id);
create index if not exists esign_document_slug_idx on public.esign_document (slug);

-- ESignSubmission -------------------------------------------------------
create table if not exists public.esign_submission (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  completed_at timestamptz,
  created_by_email text,
  created_by_name text,
  document_id text,
  sequence_type text,
  signed_document_url text,
  signer_email text,
  signer_index integer,
  signer_name text,
  signers jsonb,
  status text,
  submitted_at timestamptz,
  template_id text,
  transaction_id text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists esign_submission_touch on public.esign_submission;
create trigger esign_submission_touch before update on public.esign_submission for each row execute function public.touch_updated_date();
drop trigger if exists esign_submission_fill on public.esign_submission;
create trigger esign_submission_fill before insert on public.esign_submission for each row execute function public.fill_owner();
alter table public.esign_submission enable row level security;
-- Signing links are looked up by token inside `signers`.
create index if not exists esign_submission_signers_gin on public.esign_submission using gin (signers jsonb_path_ops);
create index if not exists esign_submission_brokerage_id_idx on public.esign_submission (brokerage_id);
create index if not exists esign_submission_document_id_idx on public.esign_submission (document_id);

-- ESignSubmitter --------------------------------------------------------
create table if not exists public.esign_submitter (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  email text,
  "order" integer,
  signed boolean,
  submission_id text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists esign_submitter_touch on public.esign_submitter;
create trigger esign_submitter_touch before update on public.esign_submitter for each row execute function public.touch_updated_date();
drop trigger if exists esign_submitter_fill on public.esign_submitter;
create trigger esign_submitter_fill before insert on public.esign_submitter for each row execute function public.fill_creator();
alter table public.esign_submitter enable row level security;
create index if not exists esign_submitter_submission_id_idx on public.esign_submitter (submission_id);

-- ESignTemplate ---------------------------------------------------------
create table if not exists public.esign_template (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  created_by_email text,
  document_url text,
  fields jsonb,
  title text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists esign_template_touch on public.esign_template;
create trigger esign_template_touch before update on public.esign_template for each row execute function public.touch_updated_date();
drop trigger if exists esign_template_fill on public.esign_template;
create trigger esign_template_fill before insert on public.esign_template for each row execute function public.fill_owner();
alter table public.esign_template enable row level security;
create index if not exists esign_template_brokerage_id_idx on public.esign_template (brokerage_id);

-- Event -----------------------------------------------------------------
create table if not exists public.event (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  date date,
  organizer_email text,
  organizer_name text,
  status text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists event_touch on public.event;
create trigger event_touch before update on public.event for each row execute function public.touch_updated_date();
drop trigger if exists event_fill on public.event;
create trigger event_fill before insert on public.event for each row execute function public.fill_owner();
alter table public.event enable row level security;
create index if not exists event_brokerage_id_idx on public.event (brokerage_id);

-- EventRSVP -------------------------------------------------------------
create table if not exists public.event_rsvp (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  checked_in boolean,
  dietary_notes text,
  event_id text,
  guests_count integer,
  status text,
  user_email text,
  user_name text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists event_rsvp_touch on public.event_rsvp;
create trigger event_rsvp_touch before update on public.event_rsvp for each row execute function public.touch_updated_date();
drop trigger if exists event_rsvp_fill on public.event_rsvp;
create trigger event_rsvp_fill before insert on public.event_rsvp for each row execute function public.fill_owner();
alter table public.event_rsvp enable row level security;
create index if not exists event_rsvp_brokerage_id_idx on public.event_rsvp (brokerage_id);
create index if not exists event_rsvp_user_email_idx on public.event_rsvp (user_email);

-- FileRepository --------------------------------------------------------
create table if not exists public.file_repository (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  category text,
  description text,
  downloads_count integer,
  file_name text,
  file_size integer,
  file_url text,
  is_featured boolean,
  tags jsonb,
  uploaded_by_email text,
  uploaded_by_name text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists file_repository_touch on public.file_repository;
create trigger file_repository_touch before update on public.file_repository for each row execute function public.touch_updated_date();
drop trigger if exists file_repository_fill on public.file_repository;
create trigger file_repository_fill before insert on public.file_repository for each row execute function public.fill_owner();
alter table public.file_repository enable row level security;
create index if not exists file_repository_brokerage_id_idx on public.file_repository (brokerage_id);

-- GeneratedContract -----------------------------------------------------
create table if not exists public.generated_contract (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  buyer_name text,
  contract_text text,
  created_by_email text,
  created_by_name text,
  property_address text,
  purchase_price numeric,
  seller_name text,
  state text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists generated_contract_touch on public.generated_contract;
create trigger generated_contract_touch before update on public.generated_contract for each row execute function public.touch_updated_date();
drop trigger if exists generated_contract_fill on public.generated_contract;
create trigger generated_contract_fill before insert on public.generated_contract for each row execute function public.fill_owner();
alter table public.generated_contract enable row level security;
create index if not exists generated_contract_brokerage_id_idx on public.generated_contract (brokerage_id);

-- GroupChat -------------------------------------------------------------
create table if not exists public.group_chat (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  created_by_email text,
  created_by_name text,
  members jsonb,
  name text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists group_chat_touch on public.group_chat;
create trigger group_chat_touch before update on public.group_chat for each row execute function public.touch_updated_date();
drop trigger if exists group_chat_fill on public.group_chat;
create trigger group_chat_fill before insert on public.group_chat for each row execute function public.fill_owner();
alter table public.group_chat enable row level security;
create index if not exists group_chat_brokerage_id_idx on public.group_chat (brokerage_id);

-- GroupMessage ----------------------------------------------------------
create table if not exists public.group_message (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  content text,
  group_id text,
  reactions jsonb,
  sender_email text,
  sender_id text,
  sender_name text,
  sender_photo text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists group_message_touch on public.group_message;
create trigger group_message_touch before update on public.group_message for each row execute function public.touch_updated_date();
drop trigger if exists group_message_fill on public.group_message;
create trigger group_message_fill before insert on public.group_message for each row execute function public.fill_owner();
alter table public.group_message enable row level security;
create index if not exists group_message_brokerage_id_idx on public.group_message (brokerage_id);
create index if not exists group_message_group_id_idx on public.group_message (group_id);

-- Idea ------------------------------------------------------------------
create table if not exists public.idea (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  admin_notes text,
  brokerage_id text,
  category text,
  description text,
  downvotes integer,
  is_anonymous boolean,
  status text,
  submitter_email text,
  submitter_name text,
  title text,
  upvotes integer,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists idea_touch on public.idea;
create trigger idea_touch before update on public.idea for each row execute function public.touch_updated_date();
drop trigger if exists idea_fill on public.idea;
create trigger idea_fill before insert on public.idea for each row execute function public.fill_owner();
alter table public.idea enable row level security;
create index if not exists idea_brokerage_id_idx on public.idea (brokerage_id);

-- IdeaPadNote -----------------------------------------------------------
create table if not exists public.idea_pad_note (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  content text,
  messages jsonb,
  title text,
  user_email text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists idea_pad_note_touch on public.idea_pad_note;
create trigger idea_pad_note_touch before update on public.idea_pad_note for each row execute function public.touch_updated_date();
drop trigger if exists idea_pad_note_fill on public.idea_pad_note;
create trigger idea_pad_note_fill before insert on public.idea_pad_note for each row execute function public.fill_creator();
alter table public.idea_pad_note enable row level security;
create index if not exists idea_pad_note_user_email_idx on public.idea_pad_note (user_email);

-- Message ---------------------------------------------------------------
create table if not exists public.message (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  content text,
  conversation_id text,
  read boolean,
  sender_email text,
  sender_name text,
  sender_role text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists message_touch on public.message;
create trigger message_touch before update on public.message for each row execute function public.touch_updated_date();
drop trigger if exists message_fill on public.message;
create trigger message_fill before insert on public.message for each row execute function public.fill_owner();
alter table public.message enable row level security;
create index if not exists message_brokerage_id_idx on public.message (brokerage_id);
create index if not exists message_conversation_id_idx on public.message (conversation_id);

-- Notification ----------------------------------------------------------
create table if not exists public.notification (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  action_url text,
  brokerage_id text,
  channel text,
  description text,
  read boolean,
  reference_id text,
  reference_type text,
  title text,
  type text,
  user_email text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists notification_touch on public.notification;
create trigger notification_touch before update on public.notification for each row execute function public.touch_updated_date();
drop trigger if exists notification_fill on public.notification;
create trigger notification_fill before insert on public.notification for each row execute function public.fill_owner();
alter table public.notification enable row level security;
create index if not exists notification_brokerage_id_idx on public.notification (brokerage_id);
create index if not exists notification_user_email_idx on public.notification (user_email);
create index if not exists notification_channel_idx on public.notification (channel);

-- Onboarding ------------------------------------------------------------
create table if not exists public.onboarding (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  agent_email text,
  agent_name text,
  brokerage_id text,
  items jsonb,
  status text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists onboarding_touch on public.onboarding;
create trigger onboarding_touch before update on public.onboarding for each row execute function public.touch_updated_date();
drop trigger if exists onboarding_fill on public.onboarding;
create trigger onboarding_fill before insert on public.onboarding for each row execute function public.fill_owner();
alter table public.onboarding enable row level security;
create index if not exists onboarding_brokerage_id_idx on public.onboarding (brokerage_id);

-- Recognition -----------------------------------------------------------
create table if not exists public.recognition (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  category text,
  from_email text,
  from_name text,
  is_anonymous boolean,
  message text,
  reactions jsonb,
  to_email text,
  to_name text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists recognition_touch on public.recognition;
create trigger recognition_touch before update on public.recognition for each row execute function public.touch_updated_date();
drop trigger if exists recognition_fill on public.recognition;
create trigger recognition_fill before insert on public.recognition for each row execute function public.fill_owner();
alter table public.recognition enable row level security;
create index if not exists recognition_brokerage_id_idx on public.recognition (brokerage_id);

-- ScheduledCall ---------------------------------------------------------
create table if not exists public.scheduled_call (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  agent_email text,
  agent_name text,
  brokerage_id text,
  scheduled_at timestamptz,
  status text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists scheduled_call_touch on public.scheduled_call;
create trigger scheduled_call_touch before update on public.scheduled_call for each row execute function public.touch_updated_date();
drop trigger if exists scheduled_call_fill on public.scheduled_call;
create trigger scheduled_call_fill before insert on public.scheduled_call for each row execute function public.fill_owner();
alter table public.scheduled_call enable row level security;
create index if not exists scheduled_call_brokerage_id_idx on public.scheduled_call (brokerage_id);

-- SignatureData ---------------------------------------------------------
create table if not exists public.signature_data (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  fields jsonb,
  ip_address text,
  signed_at timestamptz,
  signer_email text,
  signer_name text,
  submission_id text,
  user_agent text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists signature_data_touch on public.signature_data;
create trigger signature_data_touch before update on public.signature_data for each row execute function public.touch_updated_date();
drop trigger if exists signature_data_fill on public.signature_data;
create trigger signature_data_fill before insert on public.signature_data for each row execute function public.fill_creator();
alter table public.signature_data enable row level security;
create index if not exists signature_data_submission_id_idx on public.signature_data (submission_id);

-- SocialMessage ---------------------------------------------------------
create table if not exists public.social_message (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  channel text,
  content text,
  mentions jsonb,
  pinned boolean,
  pinned_by text,
  reactions jsonb,
  read_by jsonb,
  sender_email text,
  sender_name text,
  sender_photo text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists social_message_touch on public.social_message;
create trigger social_message_touch before update on public.social_message for each row execute function public.touch_updated_date();
drop trigger if exists social_message_fill on public.social_message;
create trigger social_message_fill before insert on public.social_message for each row execute function public.fill_owner();
alter table public.social_message enable row level security;
create index if not exists social_message_brokerage_id_idx on public.social_message (brokerage_id);
create index if not exists social_message_channel_idx on public.social_message (channel);

-- ThreadReply -----------------------------------------------------------
create table if not exists public.thread_reply (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  brokerage_id text,
  content text,
  message_id text,
  reactions jsonb,
  sender_email text,
  sender_name text,
  sender_photo text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists thread_reply_touch on public.thread_reply;
create trigger thread_reply_touch before update on public.thread_reply for each row execute function public.touch_updated_date();
drop trigger if exists thread_reply_fill on public.thread_reply;
create trigger thread_reply_fill before insert on public.thread_reply for each row execute function public.fill_owner();
alter table public.thread_reply enable row level security;
create index if not exists thread_reply_brokerage_id_idx on public.thread_reply (brokerage_id);

-- Transaction -----------------------------------------------------------
create table if not exists public.transaction (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  agent_email text,
  agent_name text,
  agent_net numeric,
  agent_split_percentage numeric,
  appraisal_date date,
  brokerage_fee numeric,
  brokerage_fee_flat numeric,
  brokerage_fee_percentage numeric,
  brokerage_fee_type text,
  brokerage_id text,
  buyer_name text,
  buyers jsonb,
  checklist jsonb,
  closing_date date,
  commission_amount numeric,
  commission_flat numeric,
  commission_notes text,
  commission_percentage numeric,
  commission_sale_price numeric,
  commission_type text,
  completed_dates jsonb,
  documents jsonb,
  esign_docs jsonb,
  financing_contingency_date date,
  inspection_contingency_date date,
  inspection_date date,
  loan_approval_date date,
  property_address text,
  sale_price numeric,
  seller_name text,
  sellers jsonb,
  status text,
  tc_email text,
  tc_name text,
  title_deadline_date date,
  transaction_fee numeric,
  transaction_fee_flat numeric,
  transaction_fee_percentage numeric,
  transaction_fee_type text,
  updates jsonb,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists transaction_touch on public.transaction;
create trigger transaction_touch before update on public.transaction for each row execute function public.touch_updated_date();
drop trigger if exists transaction_fill on public.transaction;
create trigger transaction_fill before insert on public.transaction for each row execute function public.fill_owner();
alter table public.transaction enable row level security;
create index if not exists transaction_brokerage_id_idx on public.transaction (brokerage_id);

-- UserBadge -------------------------------------------------------------
create table if not exists public.user_badge (
  id text primary key default replace(gen_random_uuid()::text, '-', ''),
  badge_type text,
  brokerage_id text,
  user_email text,
  extra jsonb not null default '{}'::jsonb,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now(),
  created_by text
);
drop trigger if exists user_badge_touch on public.user_badge;
create trigger user_badge_touch before update on public.user_badge for each row execute function public.touch_updated_date();
drop trigger if exists user_badge_fill on public.user_badge;
create trigger user_badge_fill before insert on public.user_badge for each row execute function public.fill_owner();
alter table public.user_badge enable row level security;
create index if not exists user_badge_brokerage_id_idx on public.user_badge (brokerage_id);
create index if not exists user_badge_user_email_idx on public.user_badge (user_email);

-- Security rules ------------------------------------------------------------
drop policy if exists activity_log_access on public.activity_log;
create policy activity_log_access on public.activity_log for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists admin_message_access on public.admin_message;
create policy admin_message_access on public.admin_message for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists agent_sales_access on public.agent_sales;
create policy agent_sales_access on public.agent_sales for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists brokerage_access on public.brokerage;
create policy brokerage_access on public.brokerage for select using (id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists brokerage_admin on public.brokerage;
create policy brokerage_admin on public.brokerage for all using ((id = public.auth_brokerage_id() and public.is_brokerage_admin()) or public.is_super_admin());
drop policy if exists brokerage_settings_access on public.brokerage_settings;
create policy brokerage_settings_access on public.brokerage_settings for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists cmas_report_access on public.cmas_report;
create policy cmas_report_access on public.cmas_report for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists channel_access on public.channel;
create policy channel_access on public.channel for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists channel_member_access on public.channel_member;
create policy channel_member_access on public.channel_member for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists client_review_access on public.client_review;
create policy client_review_access on public.client_review for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists comment_access on public.comment;
create policy comment_access on public.comment for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists compliance_attempt_access on public.compliance_attempt;
create policy compliance_attempt_access on public.compliance_attempt for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists compliance_question_access on public.compliance_question;
create policy compliance_question_access on public.compliance_question for select using (auth.uid() is not null);
drop policy if exists compliance_question_admin on public.compliance_question;
create policy compliance_question_admin on public.compliance_question for all using (public.is_brokerage_admin());
drop policy if exists compliance_training_access on public.compliance_training;
create policy compliance_training_access on public.compliance_training for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists conversation_access on public.conversation;
create policy conversation_access on public.conversation for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists culture_calendar_entry_access on public.culture_calendar_entry;
create policy culture_calendar_entry_access on public.culture_calendar_entry for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists culture_calendar_rsvp_access on public.culture_calendar_rsvp;
create policy culture_calendar_rsvp_access on public.culture_calendar_rsvp for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists dashboard_announcement_access on public.dashboard_announcement;
create policy dashboard_announcement_access on public.dashboard_announcement for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists direct_message_access on public.direct_message;
create policy direct_message_access on public.direct_message for all using (lower(sender_email) = public.auth_email() or lower(receiver_email) = public.auth_email() or public.is_super_admin()) with check (lower(sender_email) = public.auth_email() or lower(receiver_email) = public.auth_email());
drop policy if exists document_template_access on public.document_template;
create policy document_template_access on public.document_template for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists esign_audit_log_access on public.esign_audit_log;
create policy esign_audit_log_access on public.esign_audit_log for select using (public.is_super_admin() or exists (select 1 from public.esign_document d where d.id = esign_audit_log.document_id and d.brokerage_id = public.auth_brokerage_id()));
drop policy if exists esign_document_access on public.esign_document;
create policy esign_document_access on public.esign_document for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists esign_submission_access on public.esign_submission;
create policy esign_submission_access on public.esign_submission for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin() or exists (select 1 from public.esign_document d where d.id = esign_submission.document_id and d.brokerage_id = public.auth_brokerage_id())) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists esign_submitter_access on public.esign_submitter;
create policy esign_submitter_access on public.esign_submitter for select using (public.is_super_admin() or exists (select 1 from public.esign_submission s where s.id = esign_submitter.submission_id and (s.brokerage_id = public.auth_brokerage_id() or exists (select 1 from public.esign_document d where d.id = s.document_id and d.brokerage_id = public.auth_brokerage_id()))));
drop policy if exists esign_template_access on public.esign_template;
create policy esign_template_access on public.esign_template for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists event_access on public.event;
create policy event_access on public.event for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists event_rsvp_access on public.event_rsvp;
create policy event_rsvp_access on public.event_rsvp for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists file_repository_access on public.file_repository;
create policy file_repository_access on public.file_repository for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists generated_contract_access on public.generated_contract;
create policy generated_contract_access on public.generated_contract for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists group_chat_access on public.group_chat;
create policy group_chat_access on public.group_chat for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists group_message_access on public.group_message;
create policy group_message_access on public.group_message for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists idea_access on public.idea;
create policy idea_access on public.idea for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists idea_pad_note_access on public.idea_pad_note;
create policy idea_pad_note_access on public.idea_pad_note for all using (lower(user_email) = public.auth_email()) with check (lower(user_email) = public.auth_email());
drop policy if exists message_access on public.message;
create policy message_access on public.message for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists notification_access on public.notification;
create policy notification_access on public.notification for all using (lower(user_email) = public.auth_email() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or lower(user_email) = public.auth_email() or public.is_super_admin());
drop policy if exists onboarding_access on public.onboarding;
create policy onboarding_access on public.onboarding for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists recognition_access on public.recognition;
create policy recognition_access on public.recognition for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists scheduled_call_access on public.scheduled_call;
create policy scheduled_call_access on public.scheduled_call for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists signature_data_access on public.signature_data;
create policy signature_data_access on public.signature_data for select using (public.is_super_admin() or exists (select 1 from public.esign_submission s where s.id = signature_data.submission_id and (s.brokerage_id = public.auth_brokerage_id() or exists (select 1 from public.esign_document d where d.id = s.document_id and d.brokerage_id = public.auth_brokerage_id()))));
drop policy if exists social_message_access on public.social_message;
create policy social_message_access on public.social_message for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists thread_reply_access on public.thread_reply;
create policy thread_reply_access on public.thread_reply for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists transaction_access on public.transaction;
create policy transaction_access on public.transaction for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());
drop policy if exists user_badge_access on public.user_badge;
create policy user_badge_access on public.user_badge for all using (brokerage_id = public.auth_brokerage_id() or public.is_super_admin()) with check (brokerage_id = public.auth_brokerage_id() or public.is_super_admin());

-- Live updates (chat, notifications) ---------------------------------------
do $$ declare t text; begin
  foreach t in array array['notification','social_message','direct_message','group_message','message','thread_reply','conversation','admin_message','scheduled_call','culture_calendar_entry','profiles'] loop
    begin execute format('alter publication supabase_realtime add table public.%I', t);
    exception when duplicate_object then null; end;
  end loop; end $$;

-- File storage ---------------------------------------------------------------
insert into storage.buckets (id, name, public) values ('public-files', 'public-files', true)
  on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('private-files', 'private-files', false)
  on conflict (id) do nothing;
drop policy if exists "signed-in upload public" on storage.objects;
create policy "signed-in upload public" on storage.objects for insert to authenticated
  with check (bucket_id = 'public-files');
drop policy if exists "anyone read public" on storage.objects;
create policy "anyone read public" on storage.objects for select using (bucket_id = 'public-files');
-- private-files: written and read only by server routes, which hand out short-lived signed URLs.
