import assert from 'node:assert/strict';
Object.assign(process.env, { SUPABASE_URL: 'http://sb', SUPABASE_SERVICE_ROLE_KEY: 'service', SUPABASE_ANON_KEY: 'anon', HOOK_SECRET: 'hs', APP_URL: 'https://gurubroker.app' });
const seen = [];
globalThis.fetch = async (url) => { url = String(url); seen.push(url);
  if (url.includes('streetview')) return url.includes('Nowhere') ? new Response('', { status: 404 }) : new Response(new Uint8Array([255, 216, 255]), { headers: { 'content-type': 'image/jpeg' } });
  throw new Error('unexpected ' + url); };
globalThis.__users = { ann: { id: 'u1', email: 'ann@x.com' } };
globalThis.__db = { profiles: [{ id: 'u1', email: 'ann@x.com', role: 'user', brokerage_id: 'B1', extra: {} }] };
const { GET } = await import('./fn.mjs');
const get = (q, cookie) => GET(new Request(`https://gurubroker.app/api/fn/streetView?address=${encodeURIComponent(q)}`, { headers: cookie ? { cookie } : {} }));
let r = await get('12 Elm St, Chester, CT', 'gbh_at=ann');
assert.equal(r.status, 404, 'no key'); assert.match((await r.json()).problem, /GOOGLE_MAPS_API_KEY/);
process.env.GOOGLE_MAPS_API_KEY = 'gk';
r = await get('12 Elm St, Chester, CT');
assert.equal(r.status, 401, 'signed in only');
r = await get('12 Elm St, Chester, CT', 'x=1; gbh_at=ann');
assert.equal(r.status, 200); assert.equal(r.headers.get('content-type'), 'image/jpeg');
assert.ok(seen.at(-1).includes('location=12+Elm+St') && seen.at(-1).includes('key=gk'));
r = await get('1 Nowhere Rd', 'gbh_at=ann');
assert.equal(r.status, 404, 'no imagery');
globalThis.fetch = async (url) => (String(url).includes('metadata') ? new Response(JSON.stringify({ status: 'REQUEST_DENIED', error_message: 'API keys with referer restrictions cannot be used with this API.' })) : new Response('', { status: 403 }));
r = await GET(new Request('https://gurubroker.app/api/fn/streetView?check=1&address=x', { headers: { cookie: 'gbh_at=ann' } }));
const j = await r.json();
assert.equal(j.google_status, 'REQUEST_DENIED'); assert.match(j.meaning, /restrictions/); assert.equal(j.key_ends_with, '=gk'.slice(-2) === 'gk' ? 'gk' : j.key_ends_with);
r = await GET(new Request('https://gurubroker.app/api/fn/streetView?check=1'));
assert.match((await r.json()).problem, /signed in/);
console.log('street view: all checks passed');
